# shared-repo/.github/workflows/shared-workflow.yml
name: Shared CI Workflow

on:
  workflow_call:  # Allows other repos to call this workflow
    inputs:
      run-tests:
        required: false
        type: boolean
        default: true

jobs:
  aqua:
    name: Aqua scanner
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pipeline enforcer
        uses: aquasecurity/pipeline-enforcer-action@main
        with:
         #aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-key: fcakfVkkWNaWLYvs5A5qfR
          aqua-secret: 41darGQlrtq324I0HnYbO6KhNB6FKDjTrsf
         #aqua-secret: ${{ secrets.AQUA_SECRET }}

      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner:latest
        with:
          args: trivy fs --debug --sast --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
env:
    AQUA_KEY: fcakfVkkWNaWLYvs5A5qfR
    AQUA_SECRET: 41darGQlrtq324I0HnYbO6KhNB6FKDjTrsf
    #GITHUB_TOKEN: ${{ secrets.TOKEN }}
    TRIVY_RUN_AS_PLUGIN: 'aqua'
    #ACTIONS_RUNTIME_TOKEN: ${{ secrets.TOKEN }}   
    TRIVY_USERNAME: teja.chittamuri@aquasec.com
    TRIVY_PASSWORD: Jesus@saves2001
